---
title: "R Data Types"
author: "Clarissa Boyajian"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Create vector

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)

class(vec_1)
# class is numeric
typeof(vec_1)
# type is double

vec_1_e3 <- vec_1[3]
vec_1_e1 <- vec_1[1]
vec_1_e5to7 <- vec_1[5:7]

vec_1_char <- as.character(vec_1)

vec_1
vec_1_char
# output changes to have quotes around the numbers
```

```{r}
vec_2 <- c(town = "Santa Barbara", location = "Rincon n", swell = "south")

class(vec_2)
# class is character
typeof(vec_2)
# type is character
length(vec_2)
# length is 3

vec_2[2]
vec_2["location"]

vec_2_e2 <- vec_2["location"]
```

```{r}
df_1 <- data.frame(region = c("A", "B", "A", "D"), 
                   species = c("otter", "great white", "sea lion", "gray whale"),
                   count = c(12, 2, 36, 6))

class(df_1)
# class is data.frame

class(df_1$species)
# class is character

max_count <- max(df_1$count)
```

